#! /bin/sh

case "$1" in
	start)
		echo "Starting LDD module"
		/usr/bin/aesdchar_load aesdchar
		echo "attempted aesdchar"
#		/usr/bin/scull_load
		echo "scull_load scull ..."
		/etc/init.d/scull_load
		echo "module_load faulty ..."
		/etc/init.d/module_load faulty
#		/usr/bin/module_load faulty
		echo "modprobe hello"
		modprobe hello
		;;
	
	stop)
		echo "Stopping LDD module"
		/usr/bin/aesdchar_unload aesdchar
#		/usr/bin/scull_unload
		/etc/init.d/scull_unload scull
		/etc/init.d/module_unload faulty
#		/usr/bin/module_unload faulty
		rmmod hello
		;;
	
	*)
		echo "Usage: $0{start|stop}"
	exit 1
	
esac
exit 0	
